modLoader = "javafml" #mandatory
loaderVersion = "[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GNU LGPL 3.0"
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId = "tipper" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Tipper" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
logoFile = "logo.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors = "PugzAreCute" #optional
description = '''
Disables some enchants
'''
[[dependencies.tipper]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[40,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.tipper]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"